# Generated by Django 5.0 on 2024-09-05 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات اصلی')),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='ابعاد')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='وزن (Kg)')),
                ('cpu', models.CharField(blank=True, max_length=255, null=True, verbose_name='سری پردازنده')),
                ('cpu_frequency', models.FloatField(blank=True, null=True, verbose_name='فرکانس کاری پردازنده (GHz)')),
                ('cpu_cache', models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه\u200cی کش (MB)')),
                ('cpu_core', models.CharField(blank=True, max_length=255, null=True, verbose_name='تعداد هسته')),
                ('cpu_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات تکمیلی پردازنده')),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='ابعاد صفحه\u200cنمایش')),
                ('resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='وضوح تصویر')),
                ('panel_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع پنل')),
                ('refresh_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='نرخ نوسازی تصویر')),
                ('screen_cover', models.CharField(blank=True, max_length=255, null=True, verbose_name='پوشش صفحه نمایش')),
                ('touch_screen', models.BooleanField(default=False, verbose_name='صفحه\u200cنمایش لمسی')),
                ('additional_display_features', models.TextField(blank=True, null=True, verbose_name='سایر ویژگی\u200cهای نمایشگر')),
                ('ram_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع حافظه\u200cی رم')),
                ('ram_bus', models.CharField(blank=True, max_length=255, null=True, verbose_name='باس رم (MHz)')),
                ('ram_upgradable', models.BooleanField(default=False, verbose_name='قابلیت ارتقای رم')),
                ('internal_memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='ظرفیت حافظه داخلی')),
                ('internal_memory_upgradable', models.BooleanField(default=False, verbose_name='قابلیت ارتقا حافظه داخلی')),
                ('gpu_manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='سازنده پردازنده\u200c گرافیکی')),
                ('gpu_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='مدل پردازنده\u200c گرافیکی')),
                ('gpu_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع پردازنده\u200c گرافیکی')),
                ('gpu_memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه پردازنده\u200c گرافیکی')),
                ('gpu_ram_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع رم پردازنده\u200c گرافیکی')),
                ('wifi_network', models.BooleanField(default=False, verbose_name='شبکه Wi-Fi')),
                ('wireless_communication_info', models.TextField(blank=True, null=True, verbose_name='توضیحات شبکه Wi-Fi')),
                ('bluetooth', models.BooleanField(default=False, verbose_name='بلوتوث')),
                ('bluetooth_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات بلوتوث')),
                ('lan', models.BooleanField(default=False, verbose_name='درگاه LAN')),
                ('usb_3_ports_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد درگاه USB 3.0 Type A و بالاتر')),
                ('usb_2_ports_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد درگاه USB 2.0 Type A')),
                ('usb_c_ports_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد درگاه USB Type C')),
                ('vga_port', models.BooleanField(default=False, verbose_name='VGA')),
                ('hdmi_port', models.BooleanField(default=False, verbose_name='HDMI')),
                ('card_reader', models.BooleanField(default=False, verbose_name='درگاه کارت\u200cخوان')),
                ('thunderbolt_support', models.BooleanField(default=False, verbose_name='پشتیبانی از تاندربولت')),
                ('headphone_microphone_jack', models.BooleanField(default=False, verbose_name='جک هدفون/میکروفن')),
                ('battery', models.CharField(blank=True, max_length=255, null=True, verbose_name='حجم باتری')),
                ('battery_charge', models.CharField(blank=True, max_length=255, null=True, verbose_name='شارژدهی باتری')),
                ('charger_power', models.CharField(blank=True, max_length=255, null=True, verbose_name='توان شارژر')),
                ('speakers_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسپیکر')),
                ('webcam', models.BooleanField(default=False, verbose_name='وبکم')),
                ('webcam_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وبکم')),
                ('optical_drive', models.BooleanField(default=False, verbose_name='درایو نوری')),
                ('backlit_keyboard', models.BooleanField(default=False, verbose_name='کیبورد با نور پس\u200cزمینه')),
                ('fingerprint_sensor', models.BooleanField(default=False, verbose_name='حسگر اثر انگشت')),
                ('alternative_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام دیگر')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام برند')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='رنگ')),
                ('price_increase', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='افزایش قیمت به ازای انتخاب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ های محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='دسته بندی ها'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product-gallery', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product_module.product')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='آی پی کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید محصول',
                'verbose_name_plural': 'بازدیدهای محصول',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='ظرفیت رم')),
                ('price_increase', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='افزایش قیمت به ازای انتخاب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'حافظه رم محصول',
                'verbose_name_plural': 'حافظه رم محصولات',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='ظرفیت حافظه')),
                ('price_increase', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='افزایش قیمت به ازای انتخاب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'حافظه محصول',
                'verbose_name_plural': 'حافظه محصولات',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=150, verbose_name='گارانتی')),
                ('price_increase', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='افزایش قیمت به ازای انتخاب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گارانتی',
                'verbose_name_plural': 'گارانتی ها',
            },
        ),
    ]
