# Generated by Django 5.0 on 2024-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='price_increase',
            field=models.IntegerField(verbose_name='افزایش قیمت به ازای انتخاب'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price_increase',
            field=models.IntegerField(verbose_name='افزایش قیمت به ازای انتخاب'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price_increase',
            field=models.IntegerField(verbose_name='افزایش قیمت به ازای انتخاب'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='price_increase',
            field=models.IntegerField(verbose_name='افزایش قیمت به ازای انتخاب'),
        ),
    ]
