# Generated by Django 5.0 on 2024-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر برند'),
        ),
    ]
