# Generated by Django 5.0 on 2024-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productbrand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدل پردازنده'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_processor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سازنده پردازنده'),
        ),
    ]
