# Generated by Django 5.0 on 2024-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_display_features',
            field=models.TextField(blank=True, null=True, verbose_name='سایر ویژگی\u200cهای نمایشگر'),
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام دیگر'),
        ),
        migrations.AddField(
            model_name='product',
            name='backlit_keyboard',
            field=models.BooleanField(default=False, verbose_name='کیبورد با نور پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حجم باتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بلوتوث'),
        ),
        migrations.AddField(
            model_name='product',
            name='card_reader',
            field=models.BooleanField(default=False, verbose_name='کارت\u200cخوان'),
        ),
        migrations.AddField(
            model_name='product',
            name='charger_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شارژر'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رنگ های موجود'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پردازنده مرکزی'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_cache',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه\u200cی کش'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='فرکانس کاری پردازنده (GHz)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_info',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات تکمیلی پردازنده'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ابعاد'),
        ),
        migrations.AddField(
            model_name='product',
            name='dvi_port',
            field=models.BooleanField(default=False, verbose_name='DVI'),
        ),
        migrations.AddField(
            model_name='product',
            name='fingerprint_sensor',
            field=models.BooleanField(default=False, verbose_name='حسگر اثر انگشت'),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پردازنده\u200c گرافیکی'),
        ),
        migrations.AddField(
            model_name='product',
            name='hdmi_port',
            field=models.BooleanField(default=False, verbose_name='HDMI'),
        ),
        migrations.AddField(
            model_name='product',
            name='headphone_microphone_jack',
            field=models.BooleanField(default=False, verbose_name='جک هدفون/میکروفن'),
        ),
        migrations.AddField(
            model_name='product',
            name='network_port',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پورت شبکه'),
        ),
        migrations.AddField(
            model_name='product',
            name='optical_drive',
            field=models.BooleanField(default=False, verbose_name='درایو نوری'),
        ),
        migrations.AddField(
            model_name='product',
            name='panel_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع پنل'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه\u200cی رم'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع حافظه\u200cی رم'),
        ),
        migrations.AddField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نرخ نوسازی تصویر'),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رزولوشن'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_cover',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پوشش صفحه نمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اندازه صفحه\u200cنمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='speakers_info',
            field=models.TextField(blank=True, null=True, verbose_name='اسپیکر'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه\u200cی ذخیره\u200cسازی'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع حافظه\u200cی ذخیره\u200cسازی'),
        ),
        migrations.AddField(
            model_name='product',
            name='thunderbolt_support',
            field=models.BooleanField(default=False, verbose_name='پشتیبانی از تاندربولت'),
        ),
        migrations.AddField(
            model_name='product',
            name='touch_screen',
            field=models.BooleanField(blank=True, null=True, verbose_name='صفحه\u200cنمایش لمسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='usb_2_ports_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد درگاه USB 2.0 Type A'),
        ),
        migrations.AddField(
            model_name='product',
            name='usb_3_ports_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد درگاه USB 3.0 Type A و بالاتر'),
        ),
        migrations.AddField(
            model_name='product',
            name='usb_c_ports_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد درگاه USB Type C'),
        ),
        migrations.AddField(
            model_name='product',
            name='vga_port',
            field=models.BooleanField(default=False, verbose_name='VGA'),
        ),
        migrations.AddField(
            model_name='product',
            name='webcam_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات وبکم'),
        ),
        migrations.AddField(
            model_name='product',
            name='webcam_info',
            field=models.TextField(blank=True, null=True, verbose_name='وبکم'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن'),
        ),
        migrations.AddField(
            model_name='product',
            name='wireless_communication_info',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات ارتباطات بی\u200cسیم'),
        ),
        migrations.AddField(
            model_name='product',
            name='wireless_network',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شبکه\u200cی بی\u200cسیم'),
        ),
    ]
