# Generated by Django 5.0 on 2024-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_product_additional_display_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='speakers_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسپیکر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='webcam_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وبکم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن (Kg)'),
        ),
    ]
