# Generated by Django 5.0 on 2024-09-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_rename_article_productcomment_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
