# Generated by Django 5.0 on 2024-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_product_speakers_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_capacity',
        ),
        migrations.AddField(
            model_name='product',
            name='ram_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='(جدا سازی با ,)حافظه\u200cی رم'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه\u200cی ذخیره\u200cسازی(جدا سازی با ,)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='(جدا سازی با ,)گارانتی'),
        ),
    ]
