# Generated by Django 5.0 on 2024-08-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_rename_color_product_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
    ]
