# Generated by Django 5.0 on 2024-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_rename_colors_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, null=True, verbose_name='رنگ های موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_options',
            field=models.JSONField(blank=True, null=True, verbose_name='حافظه\u200cی رم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_options',
            field=models.JSONField(blank=True, null=True, verbose_name='حافظه\u200cی ذخیره\u200cسازی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.JSONField(blank=True, null=True, verbose_name='گارانتی'),
        ),
    ]
