# Generated by Django 5.0 on 2024-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_product_color_alter_product_ram_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سری پردازنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cpu_cache',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه\u200cی کش (MB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وضوح تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ابعاد صفحه\u200cنمایش'),
        ),
    ]
