# Generated by Django 5.0 on 2024-08-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_product_cpu_alter_product_cpu_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram_upgradable',
            field=models.BooleanField(blank=True, null=True, verbose_name='قابلیت ارتقای رم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_options',
            field=models.JSONField(blank=True, null=True, verbose_name='ظرفیت حافظه\u200cی رم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='(MHz)باس رم'),
        ),
    ]
