# Generated by Django 5.0 on 2024-08-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_product_ram_upgradable_alter_product_ram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram_bus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='(MHz)باس رم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع حافظه\u200cی رم'),
        ),
    ]
