# Generated by Django 5.0 on 2024-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_product_ram_bus_alter_product_ram_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu_core',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تعداد هسته'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_bus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='باس رم (MHz)'),
        ),
    ]
