# Generated by Django 5.0 on 2024-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_product_cpu_core_alter_product_ram_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storage_options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_type',
        ),
        migrations.AddField(
            model_name='product',
            name='hdd_memory',
            field=models.JSONField(blank=True, null=True, verbose_name='ظرفیت حافظه HDD'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_memory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ظرفیت حافظه داخلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_memory_upgradable',
            field=models.BooleanField(blank=True, null=True, verbose_name='قابلیت ارتقا حافظه داخلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd_memory',
            field=models.JSONField(blank=True, null=True, verbose_name='ظرفیت حافظه SSD'),
        ),
    ]
