# Generated by Django 5.0 on 2024-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_remove_product_storage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gpu',
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سازنده پردازنده\u200c گرافیکی'),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_memory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حافظه پردازنده\u200c گرافیکی'),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدل پردازنده\u200c گرافیکی'),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_ram_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع رم پردازنده\u200c گرافیکی'),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع پردازنده\u200c گرافیکی'),
        ),
    ]
