# Generated by Django 5.0 on 2024-08-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_remove_product_gpu_product_gpu_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dvi_port',
        ),
        migrations.RemoveField(
            model_name='product',
            name='network_port',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wireless_network',
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات بلوتوث'),
        ),
        migrations.AddField(
            model_name='product',
            name='lan',
            field=models.BooleanField(blank=True, null=True, verbose_name='درگاه LAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='wifi_network',
            field=models.BooleanField(default=False, verbose_name='شبکه Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bluetooth',
            field=models.BooleanField(blank=True, null=True, verbose_name='بلوتوث'),
        ),
        migrations.AlterField(
            model_name='product',
            name='card_reader',
            field=models.BooleanField(default=False, verbose_name='درگاه کارت\u200cخوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wireless_communication_info',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات شبکه Wi-Fi'),
        ),
    ]
