# Generated by Django 5.0 on 2024-08-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_remove_product_dvi_port_remove_product_network_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='charger_info',
        ),
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='باتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_charge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شارژدهی باتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='charger_power',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توان شارژر'),
        ),
    ]
