# Generated by Django 5.0 on 2024-08-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_remove_product_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='webcam_info',
        ),
        migrations.AddField(
            model_name='product',
            name='webcam',
            field=models.BooleanField(blank=True, null=True, verbose_name='وبکم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حجم باتری'),
        ),
    ]
