# Generated by Django 5.0 on 2024-08-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_remove_product_webcam_info_product_webcam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bluetooth',
            field=models.BooleanField(default=False, verbose_name='بلوتوث'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_memory_upgradable',
            field=models.BooleanField(default=False, verbose_name='قابلیت ارتقا حافظه داخلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lan',
            field=models.BooleanField(default=False, verbose_name='درگاه LAN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_upgradable',
            field=models.BooleanField(default=False, verbose_name='قابلیت ارتقای رم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='touch_screen',
            field=models.BooleanField(default=False, verbose_name='صفحه\u200cنمایش لمسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='webcam',
            field=models.BooleanField(default=False, verbose_name='وبکم'),
        ),
    ]
