# Generated by Django 5.0 on 2024-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رم'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حافظه'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='گارانتی'),
        ),
    ]
