# Generated by Django 5.0 on 2024-09-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_alter_orderdetail_color_alter_orderdetail_ram_and_more'),
        ('product_module', '0002_alter_color_price_increase_alter_ram_price_increase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='ram',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.ram', verbose_name='رم'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='storage',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.storage', verbose_name='حافظه'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='warranty',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.warranty', verbose_name='گارانتی'),
        ),
    ]
