# Generated by Django 5.0 on 2024-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0007_alter_orderdetail_count_alter_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
