# Generated by Django 5.0 on 2024-09-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_sitesetting_map_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'verbose_name': 'بنر\u200cهای صفحه اصلی', 'verbose_name_plural': 'بنرهای صفحه اصلی'},
        ),
        migrations.RemoveField(
            model_name='sitebanner',
            name='position',
        ),
    ]
