# Generated by Django 5.0 on 2024-09-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_sitebanner_options_remove_sitebanner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='icon',
            field=models.ImageField(default='', upload_to='images/icons', verbose_name='آیکون بنر'),
        ),
    ]
