# Generated by Django 5.0 on 2024-09-19 19:51

import site_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_alter_sitebanner_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='icon',
            field=models.FileField(upload_to='images/icons/', validators=[site_module.models.validate_svg_file], verbose_name='آیکون بنر'),
        ),
    ]
