# Generated by Django 5.0 on 2024-09-20 11:04

import site_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_sitebanner_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='url_title',
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='icon',
            field=models.FileField(upload_to='static/images/icons/', validators=[site_module.models.validate_svg_file], verbose_name='آیکون بنر'),
        ),
    ]
