# Generated by Django 5.0 on 2024-09-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_product_stock'),
        ('site_module', '0007_remove_slider_url_title_alter_sitebanner_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebanner',
            name='url',
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دسته بندی مرتبط'),
        ),
    ]
