# Generated by Django 5.0 on 2024-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن'),
        ),
    ]
