# Generated by Django 5.0 on 2024-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_remove_contactus_email_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره تلفن'),
        ),
    ]
