# Generated by Django 5.0 on 2024-08-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
